export const calandar_theme = {
    calendarBackground: '#fff',
          textSectionTitleColor: '#b6c1cd',
          selectedDayBackgroundColor: '#1E263B',
          selectedDayTextColor: '#fff',
          todayBackgroundColor: '#6366f1',
          todayTextColor: '#fff',
          dayTextColor: '#2d4150',
          textDisabledColor: '#d9e1e8',
          dotColor: '#1E263B',
          selectedDotColor: '#fff',
          arrowColor: '#1E263B',
          monthTextColor: '#1E263B',
        //   textDayFontFamily: 'monospace',
        //   textMonthFontFamily: 'monospace',
        //   textDayHeaderFontFamily: 'monospace',
          textDayFontSize: 16,
          textMonthFontSize: 16,
          textDayHeaderFontSize: 16,
}